### ISSUE TITLE
error: possibly undefined macro: AC_PROG_INTLTOOL

### ISSUE THREAD

**Issue by tfKamran** [masami256/backlight-applet#2]
I tried `./autogen.sh` with and without sudo, I get the same error.

```
+ '[' x '!=' x ']'
+ aclocal
+ autoheader
+ AUTOMAKE=automake-1.11
+ libtoolize -c --automake --force
./autogen.sh: line 13: libtoolize: command not found
+ AUTOMAKE=automake-1.11
+ intltoolize -c --automake --force
./autogen.sh: line 14: intltoolize: command not found
+ automake-1.11 --add-missing --copy --include-deps
./autogen.sh: line 15: automake-1.11: command not found
+ autoconf
configure.ac:5: error: possibly undefined macro: AC_PROG_INTLTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:11: error: possibly undefined macro: AC_PROG_LIBTOOL
+ rm -rf autom4te.cache
```

Am I missing on some dependency that's not mentioned in the README.md?

> I am on Fedora 22 and have installed the packages mentioned in the README.md

**Comment by masami256** [comment]
Hi,

According to your log, autogen.sh uses old automake version. so I updated and pushed it.
so, this commit should following error.

```
./autogen.sh: line 15: automake-1.11: command not found
```

However, following log,  it seems you need to install intltool package.

```
./autogen.sh: line 13: libtoolize: command not found
```

Please pull latest code and install libtool then try run autothen.sh. I hope your problem is fixed.
I tested Fedora 22 LXDE spin to  build.

**Comment by tfKamran** [comment]
Thanks it worked!
